apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
spec:
  selector:
    matchLabels:
      app: ctse-payment-service
  template:
    metadata:
      labels:
        app: ctse-payment-service
    spec:
      containers:
        - name: ctse-payment-service
          image: hansithara97/payment-service
          resources:
            limits:
              memory: "1280Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080