apiVersion: v1
kind: Service
metadata:
  name: ctsepaymentservice-service
spec:
  selector:
    app: CtsePaymentService
  ports:
    - targetPort: 8080
      name: port80
      port: 80
      protocol: TCP