apiVersion: v1
kind: Service
metadata:
  name: ctse-payment-service
spec:
  selector:
    app: ctse-payment-service-aks
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: port80
      protocol: TCP