apiVersion: v1
kind: Service
metadata:
  name: payment-service-deployment
spec:
  ports:
    - port: 8086
      protocol: TCP
      targetPort: 8080
  selector:
    app: ctse-payment-service
  type: LoadBalancer
status:
  loadBalancer: {}